---
title: "Lab 1"
author: "Hongyi zhan & Oyundari Batbayar"
date: "2023-09-09"
output: html_document
---

# 5A,B

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
data = read_csv('video_games_fall_2023.csv')
attach(data)
data <- cbind(data, 'Nintendo'=ifelse(publisher=="Nintendo", 1, 0))
model5 <- lm(score ~ release_year+as.factor(Nintendo), data = data)
summary(model5)
```

With other factors being fixed, the average score for the game that was published by Nintendo would have scored 6.3 points less than the game that was published by any other.

# 5C

```{r}
# Subset the data for Nintendo and non-Nintendo
nintendo_data <- data[data$Nintendo == 1, ]
non_nintendo_data <- data[data$Nintendo == 0, ]

# Create a scatterplot for Nintendo
plot(nintendo_data$release_year, nintendo_data$score, col = "green", pch = 15,
     xlab = "Release year", ylab = "Score", xlim = c(min(data$release_year), max(data$release_year)),ylim = y_range <- range(data$score))

# Add a linear regression line for Nintendo
abline(lm(score ~ release_year, data = nintendo_data), col = "green", lwd = 2, lty = 2)

# Add points and a linear regression line for non-Nintendo
points(non_nintendo_data$release_year, non_nintendo_data$score, col = "blue", pch = 0)
abline(lm(score ~ release_year, data = non_nintendo_data), col = "blue", lwd = 2, lty = 2)

# Add a legend
legend("bottomleft", legend = c("Nintendo", "Non-Nintendo"), col = c("green", "blue"), pch = 15, lty = 2,
       lwd = 2)

# Add a title
title(main = "Relationship between the Score in different release year \n for publish by Nintendo and others")

```

# 6A

```{r}
length(table(genre))
table(genre)
```

# 6B,C,E

```{r}
model6 <- lm(score ~ relevel(as.factor(genre), ref = "Racing"), data = data)
summary(model6)
```

# 6D

```{r}
model7 <- lm(score ~ relevel(as.factor(genre), ref = "Shooter"), data = data)
summary(model7)
```

# 7A,B

```{r}
data2 <- cbind(data, 'Strategy'=ifelse(genre=="Strategy", 1, 0))
model8 <- lm(score ~ as.factor(Nintendo)+as.factor(Strategy)+as.factor(Nintendo)*as.factor(Strategy), data = data2)
summary(model8)
```

# 7C

```{r}
model9 <- lm(score ~ as.factor(Nintendo)+release_year+as.factor(Nintendo)*release_year, data = data)
summary(model9)

plot(nintendo_data$release_year, nintendo_data$score, col = "green", pch = 17,
     xlab = "Release year", ylab = "Score", xlim = c(min(data$release_year), max(data$release_year)),ylim = y_range <- range(data$score))

# Add a linear regression line for Nintendo
abline(109.83809+844.70328,-0.01983-0.41757, col = "green", lwd = 2, lty = 2)

# Add points and a linear regression line for non-Nintendo
points(non_nintendo_data$release_year, non_nintendo_data$score, col = "blue", pch = 2)
abline(109.83809,-0.01983, col = "blue", lwd = 2, lty = 2)

# Add a legend
legend("bottomleft", legend = c("Nintendo", "Non-Nintendo"), col = c("green", "blue"), pch = 2, lty = 2,
       lwd = 2)

# Add a title
title(main = "Relationship between the Score in different release year \n for publish by Nintendo and others")

```
